### ISSUE TITLE
Bad $sourcePath for bower folder

### ISSUE THREAD

**Issue by etzzzz** [RomeroMsk/yii2-chosen#12]
ChosenAsset.php
public $sourcePath = '@vendor/bower/chosen';

ChosenBootstrapAsset.php
public $sourcePath = '@vendor/bower/chosen-bootstrap';

You should use alias '@bower' not '@vendor/bower' because at least my composer installed all bower assets under 'vendor/bower/bower-assets'. And this was the problem because your extension was looking into wrong path (vendor/bower/chosen but actual path is vendor/bower/bower-assets/chosen). 

Yii2 creates @bower alias automatically when bootstrapping that corresponds to current application.

All my other third-party extensions are also using '@bower' instead of '@vendor/bower'.

**Comment by RomeroMsk** [comment]
Create a PR, please.

**Comment by etzzzz** [comment]
Hey

Sorry but i'm not actually familiar with GIT. I installed this extension
via composer.

2016-06-07 16:30 GMT+03:00 RomeroMsk <notifications@github.com>:

**Comment by RomeroMsk** [comment]
Fixed.
