### ISSUE TITLE
How to set selected options?

### ISSUE THREAD

**Issue by hanie-hadadi** [RomeroMsk/yii2-chosen#14]
I have a activeform for update a Video information and it has a category field . I use yii2-chosen for show category. but this video has some default category how can i show them in the other words how can I show selected options in select tag? 
`<?= $form->field($model, 'tag')->widget(
        Chosen::className(), [
        'items' => [1 => 'First item', 2 => 'Second item', 3 => 'Third item'],
        'multiple' => true,
        'clientOptions' => [
            'search_contains' => true,
            'single_backstroke_delete' => false,
        ],
    ]);?>`

for example in this part of code I want to `first item` be selected

**Comment by RomeroMsk** [comment]
You should deal with `$model->tag` to set the widget value, as with any other model attribute.

**Comment by hanie-hadadi** [comment]
thanks so much for your quick answer
