### ISSUE TITLE
how i can disabled value?

### ISSUE THREAD

**Issue by shahovkit** [RomeroMsk/yii2-chosen#15]
https://harvesthq.github.io/chosen/options.html#attributes
How added attribute disabled via widget

**Comment by shahovkit** [comment]
Thanks, but i mean disabled only one value

**Comment by RomeroMsk** [comment]
It should work pretty same as Yii2 [Html::listBox()](http://www.yiiframework.com/doc-2.0/yii-helpers-basehtml.html#listBox()-detail).
```php
<?= $form->field($model, 'selectable_attr')->widget(
    Chosen::className(), [
        'items' => [1 => 'First item', 2 => 'Second item', 3 => 'Third item'],
        'options' => [
            'options' => [3 => ['disabled' => true]],
        ],
]);?>
```

**Comment by shahovkit** [comment]
it's don't work(

**Comment by shahovkit** [comment]
Thanks, it's work.
it's a pity that is not an array

**Comment by bogdik** [comment]
For convenience [this](https://github.com/bogdik/yii2-chosen/commit/556cd7d31d04db097885ed8fa243a2890bbcde7b)
Just 'disablesArray' => [...],
