### ISSUE TITLE
UNABLE TO INSTALL THIS EXTENSION IN YII2

### ISSUE THREAD

**Issue by khalid84** [RomeroMsk/yii2-chosen#7]
I ma unable to install this extension in yii2. composer shows error when i run this command
>composer require "nex/yii2-chosen" "*"
Deprecation Notice: The Composer\Package\LinkConstraint\MultiConstraint class is
 deprecated, use Composer\Semver\Constraint\MultiConstraint instead. in phar://C
:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Package/LinkConstrain
t/MultiConstraint.php:17
Deprecation Notice: The Composer\Package\LinkConstraint\LinkConstraintInterface
interface is deprecated, use Composer\Semver\Constraint\ConstraintInterface inst
ead. in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Packa
ge/LinkConstraint/LinkConstraintInterface.php:17
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package dbtek/chosen-bootstrap could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package nex/yii2-chosen could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

please help ASAP
i need it in yii2 else show me the process for manual installation of this great extension.

**Comment by RomeroMsk** [comment]
This is not an extension problem. First of all, you have an old version of composer (look at deprecation notices). Run `composer self-update` to renew it.
Second: I can not reproduce your problem. Just installed my package on fresh system:
```
php composer.phar require "nex/yii2-chosen" "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing nex/yii2-chosen (dev-master 881afa0)
    Cloning 881afa090ff11183052aebeb61d3dacd54933da9

Writing lock file
Generating autoload files
```
Third: I see you have errors not only for my package, but also for `dbtek/chosen-bootstrap`. It can be some common problem.

**Comment by khalid84** [comment]
Thanks for your reply,
Sir i already updated my composer but still i am unable to install this extension. ? :( :(
I really need it. please help me 
my composer command shows - 

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package dbtek/chosen-bootstrap could not be found in any ver
sion, there may be a typo in the package name.
  Problem 2
    - The requested package nex/yii2-chosen could not be found in any version, t
here may be a typo in the package name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.
![cmd](https://cloud.githubusercontent.com/assets/15627427/11176838/c4472388-8c66-11e5-8135-b9a74fbd6f05.PNG)

**Comment by RomeroMsk** [comment]
Did you read the mentioned discussion? What is the `minimum-stability` setting of your project? If it is not `dev` (`stable` by default), it can be the reason.
