### ISSUE TITLE
Make "No results found" editable by the user.

### ISSUE THREAD

**Issue by qdii** [RomeroMsk/yii2-chosen#8]
The sentence "No results found" is hard-coded. It would be nice for an user to be able to change it through the Chosen object's settings.

**Comment by RomeroMsk** [comment]
You can translate it via messages for your app language.

**Comment by ezoterik** [comment]
I have the same problem. If we can specify `placeholder_text_*` via settings, then why can't we do the same for `no_results_text`?

**Comment by RomeroMsk** [comment]
PR is welcome.

**Comment by RomeroMsk** [comment]
Merged, thanks.
